development:
  db:
    host: localhost
    port: 3306
    database: dev_db
    
staging:
  db:
    host: staging-db.example.com
    port: 3306
    database: staging_db
    
production:
  db:
    host: prod-db.example.com
    port: 3306
    database: prod_db 