development:
  db:
    username: dev_user
    password: dev_pass
    
staging:
  db:
    username: staging_user
    password: staging_pass
    
production:
  db:
    username: prod_user
    password: prod_pass 